name: Install, Test and Lint

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, reopened]

jobs:
  install-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 20
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Typescript
        run: npx tsc

      - name: Test
        run: npm run test
